Upgrade GHA runner OS image
containerd/cgroups pull request #249
Opened 2022-10-24 21:47 UTC by austinvazquez

Updates the GitHub action CI workflow to use the ubuntu-22.04 image since the ubuntu-18.04 image has been marked deprecated.

Signed-off-by: Austin Vazquez <macedonv@amazon.com>

2022-10-24 21:51 UTC, austinvazquez commented on .github/workflows/ci.yml
> -        os: [ubuntu-18.04, ubuntu-22.04]
Both 20.04 and 22.04 images use the same Linux kernel version, 5.15.0-1022-azure, so it didn't make sense to test both.

2022-10-27 15:12 UTC, estesp commented
@AkihiroSuda do we lose cgroups v1 testing if we move to 22.04? I thought I remembered that 22.04 defaults to cgroups v2 but maybe I'm wrong.

2022-10-27 16:13 UTC, AkihiroSuda commented
> @AkihiroSuda do we lose cgroups v1 testing if we move to 22.04? I thought I remembered that 22.04 defaults to cgroups v2 but maybe I'm wrong.

Yes, so we need to use 20.04, not 22.04

2022-10-27 16:14 UTC, AkihiroSuda requested changes
https://github.com/containerd/cgroups/pull/249#issuecomment-1293765241

2022-10-27 17:22 UTC, austinvazquez commented
Thanks for the clarification @AkihiroSuda. Added a comment to remind the next person once Ubuntu 20.04 goes EOL.

2022-10-27 19:35 UTC, AkihiroSuda approved these changes

2022-10-27 19:37 UTC, merged