[WIP] NewSystemd handles UnitExists when starting units
containerd/cgroups pull request #290
Opened 2023-04-23 21:52 UTC by mmerkes

As done in this runc PR
https://github.com/opencontainers/runc/pull/3782,
UnitExists errors are no longer ignored when starting units. If it already exists, we attempt to reset the failed unit and retry once. Otherwise, we fail. See https://github.com/containerd/cgroups/issues/279 for more context.

Fixes #279 

Marked this as WIP for a few reasons:

1. The code is pretty much the same from [this runc PR](https://github.com/opencontainers/runc/pull/3782). I'm looking for guidance on how to properly attribute the reference. Not sure what does or does not need to be done there...
2. I marked a couple of `TODO` spots with questions regarding the implementing or things that I need to do a little more research into.
3. Didn't add any testing here or do any manual testing, so considering that a TODO as well.

Sharing now for feedback and conversation on the open questions.

2023-05-20 21:42 UTC, mmerkes commented
@kolyshkin Let me know if you have feedback here since you opened the original issue and made the runc change. Tx!

2023-06-27 16:14 UTC, kolyshkin approved these changes
Alas, I am not a maintainer and can't say which uses/users this method has.

But nevertheless a fix needs to be made, because the current behavior (of not adding the container into a proper cgroup) is totally unacceptable (and can, in some circumstances, be qualified as a security issue).

So, I'm adding my non-binding LGTM, but this needs a review from the actual maintainers of this package.

2023-06-28 16:35 UTC, AkihiroSuda requested changes
Please squash commits

2023-06-28 17:45 UTC, mmerkes commented
> Please squash commits

Updated. Falsely assumed that the merge would squash. @AkihiroSuda

2023-06-28 17:49 UTC, AkihiroSuda approved these changes

2023-07-11 14:11 UTC, thaJeztah approved these changes
LGTM

2023-07-14 17:34 UTC, mmerkes commented
@AkihiroSuda This good to be merged?

2023-07-16 12:35 UTC, merged